# Generated by Django 3.2.10 on 2024-04-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.IntegerField(),
        ),
    ]
