# Generated by Django 3.2.10 on 2024-04-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.IntegerField(max_length=20),
        ),
    ]
