# Generated by Django 3.2.10 on 2024-04-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_customer_policyrecord_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrecord',
            old_name='Policy',
            new_name='policy',
        ),
    ]
